# Generated by Django 5.0.3 on 2024-03-06 19:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=400)),
                ('description', models.TextField(max_length=2000)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apdated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
