# Generated by Django 5.0.3 on 2024-03-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.TextField(max_length=100),
        ),
    ]
